import { mkdir, readFile, rename, unlink, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { generateFilesOnly, type OutputFile } from 'fumadocs-openapi';
import type { OpenAPIServer } from 'fumadocs-openapi/server';
import { assertTagDisplayNames, openapi, v5Openapi } from '../src/lib/openapi';

const projectRoot = path.resolve(import.meta.dirname, '..');
const contentRoot = path.join(projectRoot, 'content', 'api-reference');
const manifestPath = path.join(projectRoot, 'openapi', 'api-reference-generated-files.json');
const generatedMarker = 'This file was generated by Fumadocs.';

const versionTargets = [
  {
    input: openapi,
    outputPrefix: '',
    title: 'API Reference',
    extraPages: ['v5'],
  },
  {
    input: v5Openapi,
    outputPrefix: 'v5',
    title: 'v5 · Archived',
    extraPages: [],
  },
] satisfies Array<{
  input: OpenAPIServer;
  outputPrefix: string;
  title: string;
  extraPages: string[];
}>;

interface GeneratedFilesManifest {
  version: 1;
  files: string[];
}

function toManifestPath(value: string): string {
  return value.split(path.sep).join('/');
}

function resolveGeneratedPath(relativePath: string): string {
  if (path.isAbsolute(relativePath)) {
    throw new Error(`Refusing to use an absolute generated path: ${relativePath}`);
  }

  const resolved = path.resolve(contentRoot, relativePath);
  const relative = path.relative(contentRoot, resolved);

  if (!relative || relative.startsWith('..') || path.isAbsolute(relative)) {
    throw new Error(`Generated path escapes content/api-reference: ${relativePath}`);
  }

  return resolved;
}

function assertDeletableGeneratedFile(relativePath: string): void {
  const extension = path.extname(relativePath);
  if (extension !== '.mdx' && path.basename(relativePath) !== 'meta.json') {
    throw new Error(`Refusing to delete an unexpected generated file: ${relativePath}`);
  }

  resolveGeneratedPath(relativePath);
}

async function readManifest(): Promise<GeneratedFilesManifest | null> {
  try {
    const value = JSON.parse(await readFile(manifestPath, 'utf8')) as Partial<GeneratedFilesManifest>;

    if (value.version !== 1 || !Array.isArray(value.files)) {
      throw new Error('The API Reference generated-files manifest is invalid.');
    }

    for (const file of value.files) {
      if (typeof file !== 'string') {
        throw new Error('The API Reference generated-files manifest contains a non-string path.');
      }
      assertDeletableGeneratedFile(file);
    }

    return { version: 1, files: value.files };
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') return null;
    throw error;
  }
}

async function getVersionFiles(target: (typeof versionTargets)[number]): Promise<OutputFile[]> {
  return generateFilesOnly({
    input: target.input,
    per: 'operation',
    groupBy: 'tag',
    meta: true,
    includeDescription: true,
    addGeneratedComment: true,
    beforeWrite(files) {
      const meta = files.find((file) => file.path === 'meta.json');
      if (!meta) return;

      const data = JSON.parse(meta.content) as { pages?: string[] };
      meta.content = JSON.stringify(
        {
          ...data,
          title: target.title,
          pages: [...(data.pages ?? []), ...target.extraPages],
        },
        null,
        2,
      );
    },
  });
}

async function writeGeneratedFiles(files: Map<string, string>): Promise<void> {
  await Promise.all(
    [...files].map(async ([relativePath, content]) => {
      const outputPath = resolveGeneratedPath(relativePath);
      await mkdir(path.dirname(outputPath), { recursive: true });
      await writeFile(outputPath, content);
      console.log(`Generated: ${path.relative(projectRoot, outputPath)}`);
    }),
  );
}

async function removeStaleFiles(previous: GeneratedFilesManifest, expected: Set<string>) {
  const staleFiles = previous.files.filter((file) => !expected.has(file));

  for (const relativePath of staleFiles) {
    assertDeletableGeneratedFile(relativePath);
    const outputPath = resolveGeneratedPath(relativePath);

    try {
      if (path.extname(relativePath) === '.mdx') {
        const content = await readFile(outputPath, 'utf8');
        if (!content.includes(generatedMarker)) {
          throw new Error(`Refusing to delete an MDX file without the generated marker: ${relativePath}`);
        }
      }

      await unlink(outputPath);
      console.log(`Removed stale generated file: ${path.relative(projectRoot, outputPath)}`);
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error;
    }
  }
}

async function writeManifest(files: string[]): Promise<void> {
  const temporaryPath = `${manifestPath}.tmp`;
  const manifest: GeneratedFilesManifest = { version: 1, files };
  await writeFile(temporaryPath, `${JSON.stringify(manifest, null, 2)}\n`);
  await rename(temporaryPath, manifestPath);
}

async function main() {
  assertTagDisplayNames();

  const previousManifest = await readManifest();
  const generatedFiles = new Map<string, string>();

  for (const target of versionTargets) {
    const files = await getVersionFiles(target);

    for (const file of files) {
      const relativePath = toManifestPath(path.join(target.outputPrefix, file.path));
      if (generatedFiles.has(relativePath)) {
        throw new Error(`Duplicate generated API Reference path: ${relativePath}`);
      }
      assertDeletableGeneratedFile(relativePath);
      generatedFiles.set(relativePath, file.content);
    }
  }

  const expectedFiles = [...generatedFiles.keys()].sort();
  await writeGeneratedFiles(generatedFiles);

  if (previousManifest) {
    await removeStaleFiles(previousManifest, new Set(expectedFiles));
  } else {
    console.log('Created the initial generated-files manifest; no stale files were removed.');
  }

  await writeManifest(expectedFiles);
}

void main();
